CREATE TABLE TIMEREC_GROUPS(
    GROUP_ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    GROUP_NAME VARCHAR(255) NOT NULL,
    GROUP_DESCRIPTION VARCHAR(255) NOT NULL,
    USER_ID INT(11) UNSIGNED NOT NULL,
    PRIMARY KEY (GROUP_ID)
);

CREATE TABLE TIMEREC_ENTRIES(
    ENTRY_ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    ENTRY_START TIMESTAMP NOT NULL,
    ENTRY_STOP TIMESTAMP DEFAULT NULL,
    ENTRY_COMMENT TEXT,
    ENTRY_PAYED INT(1) UNSIGNED DEFAULT 0,
    USER_ID INT(11) UNSIGNED NOT NULL,
    CUSTOMER_ID INT(11) UNSIGNED NOT NULL,
    PRIMARY KEY (ENTRY_ID)
);

CREATE TABLE TIMEREC_CUSTOMERS(
    CUSTOMER_ID INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(255) NOT NULL,
    CUSTOMER_ADDRESS TEXT,
    CUSTOMER_EMAIL VARCHAR(255),
    GROUP_ID INT(11) UNSIGNED,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE TIMEREC_GROUPS_USERS(
    USER_ID INT(11) UNSIGNED NOT NULL,
    GROUP_ID INT(11) UNSIGNED NOT NULL,
    PRIMARY KEY (USER_ID, GROUP_ID)
);

ALTER TABLE TIMEREC_CUSTOMERS ADD COLUMN CUSTOMER_PHONE VARCHAR(255);

-- UPDATE TO VERSION 2

ALTER TABLE TIMEREC_GROUPS ADD COLUMN GROUP_INVITATIONCODE VARCHAR(25);